version: '3'
services:
  angular-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    container_name: angular-ui
    volumes:
       - ./app-ui:/Users/qx/code/play/ng-rx-play
       - /Users/qx/code/play/ng-rx-play/node_modules
